-- Lot 1 (05/10/2026) : ajoute aux comptes EXISTANTS les marques de départ courantes sur Vinted (liste de
-- server/src/catalogue/marques.ts au 05/10/2026). Les marques déjà présentes (sans tenir compte des majuscules) ne
-- sont pas dupliquées. Les nouveaux comptes reçoivent la liste à leur création (amorçage).
INSERT INTO "marque" ("utilisateur_id", "nom")
SELECT u."id", m."nom"
FROM "utilisateur" AS u
CROSS JOIN (VALUES
  ('Sans marque'),
  ('Adidas'),
  ('Nike'),
  ('Puma'),
  ('Reebok'),
  ('New Balance'),
  ('Asics'),
  ('Under Armour'),
  ('Fila'),
  ('Kappa'),
  ('Le Coq Sportif'),
  ('Umbro'),
  ('Champion'),
  ('Converse'),
  ('Vans'),
  ('Jordan'),
  ('Salomon'),
  ('Columbia'),
  ('The North Face'),
  ('Patagonia'),
  ('Quechua'),
  ('Decathlon'),
  ('Kalenji'),
  ('Domyos'),
  ('Lafuma'),
  ('Millet'),
  ('Helly Hansen'),
  ('Berghaus'),
  ('Mizuno'),
  ('Saucony'),
  ('Hoka'),
  ('On'),
  ('Brooks'),
  ('Diadora'),
  ('Lotto'),
  ('Ellesse'),
  ('Sergio Tacchini'),
  ('Hummel'),
  ('Macron'),
  ('Errea'),
  ('Joma'),
  ('Canterbury'),
  ('Gilbert'),
  ('Kipsta'),
  ('Wilson'),
  ('Babolat'),
  ('Head'),
  ('Rossignol'),
  ('Quiksilver'),
  ('Roxy'),
  ('Billabong'),
  ('Rip Curl'),
  ('O''Neill'),
  ('Oxbow'),
  ('Arena'),
  ('Speedo'),
  ('Lacoste'),
  ('Ralph Lauren'),
  ('Polo Ralph Lauren'),
  ('Tommy Hilfiger'),
  ('Calvin Klein'),
  ('Hugo Boss'),
  ('Boss'),
  ('Fred Perry'),
  ('Gant'),
  ('Hackett'),
  ('Burberry'),
  ('Gucci'),
  ('Louis Vuitton'),
  ('Prada'),
  ('Dior'),
  ('Chanel'),
  ('Saint Laurent'),
  ('Balenciaga'),
  ('Givenchy'),
  ('Versace'),
  ('Dolce & Gabbana'),
  ('Armani'),
  ('Emporio Armani'),
  ('Armani Exchange'),
  ('Michael Kors'),
  ('Kenzo'),
  ('Moncler'),
  ('Stone Island'),
  ('C.P. Company'),
  ('Paul Smith'),
  ('Ted Baker'),
  ('Diesel'),
  ('Moschino'),
  ('Fendi'),
  ('Valentino'),
  ('Off-White'),
  ('Maison Kitsuné'),
  ('A.P.C.'),
  ('Ami Paris'),
  ('Sandro'),
  ('Maje'),
  ('The Kooples'),
  ('Claudie Pierlot'),
  ('Zadig & Voltaire'),
  ('Ba&sh'),
  ('Sézane'),
  ('Isabel Marant'),
  ('Comptoir des Cotonniers'),
  ('Gérard Darel'),
  ('Agnès b.'),
  ('Longchamp'),
  ('Lancel'),
  ('Furla'),
  ('Guess'),
  ('Desigual'),
  ('Pepe Jeans'),
  ('Replay'),
  ('G-Star Raw'),
  ('Scotch & Soda'),
  ('Napapijri'),
  ('Superdry'),
  ('Timberland'),
  ('Dr. Martens'),
  ('Clarks'),
  ('UGG'),
  ('Birkenstock'),
  ('Geox'),
  ('Kickers'),
  ('Palladium'),
  ('Camper'),
  ('Mephisto'),
  ('Paraboot'),
  ('Church''s'),
  ('Weston'),
  ('Levi''s'),
  ('Lee'),
  ('Wrangler'),
  ('Carhartt'),
  ('Carhartt WIP'),
  ('Dickies'),
  ('Edwin'),
  ('Kaporal'),
  ('Teddy Smith'),
  ('Lee Cooper'),
  ('Jack & Jones'),
  ('Only'),
  ('Vero Moda'),
  ('Kiabi'),
  ('Dockers'),
  ('Chevignon'),
  ('Schott'),
  ('Redskins'),
  ('Freeman T. Porter'),
  ('Le Temps des Cerises'),
  ('Salsa'),
  ('Mustang'),
  ('Tiffosi'),
  ('Supreme'),
  ('Stüssy'),
  ('The Hundreds'),
  ('Obey'),
  ('Huf'),
  ('Palace'),
  ('Bape'),
  ('Kith'),
  ('Fear of God'),
  ('Essentials'),
  ('Corteiz'),
  ('Trapstar'),
  ('Nike ACG'),
  ('Kangol'),
  ('Alpha Industries'),
  ('Avirex'),
  ('Von Dutch'),
  ('Ed Hardy'),
  ('Element'),
  ('DC Shoes'),
  ('Etnies'),
  ('Volcom'),
  ('Hurley'),
  ('Santa Cruz'),
  ('Thrasher'),
  ('Dime'),
  ('Patta'),
  ('Arte Antwerp'),
  ('Ninety Percent'),
  ('Sixth June'),
  ('Project X Paris'),
  ('Unkut'),
  ('Benson & Cherry'),
  ('Zara'),
  ('H&M'),
  ('Mango'),
  ('Bershka'),
  ('Pull&Bear'),
  ('Stradivarius'),
  ('Massimo Dutti'),
  ('Uniqlo'),
  ('Primark'),
  ('Shein'),
  ('Asos'),
  ('Boohoo'),
  ('PrettyLittleThing'),
  ('New Look'),
  ('Topshop'),
  ('Urban Outfitters'),
  ('Weekday'),
  ('Monki'),
  ('& Other Stories'),
  ('COS'),
  ('Arket'),
  ('Gap'),
  ('Old Navy'),
  ('Abercrombie & Fitch'),
  ('Hollister'),
  ('American Eagle'),
  ('Celio'),
  ('Jules'),
  ('Brice'),
  ('Bonobo'),
  ('Promod'),
  ('Camaïeu'),
  ('Cache Cache'),
  ('Pimkie'),
  ('Jennyfer'),
  ('Naf Naf'),
  ('Morgan'),
  ('Etam'),
  ('Undiz'),
  ('Springfield'),
  ('Esprit'),
  ('s.Oliver'),
  ('Tom Tailor'),
  ('Benetton'),
  ('Okaïdi'),
  ('Tape à l''œil'),
  ('Vertbaudet'),
  ('Petit Bateau'),
  ('Jacadi'),
  ('Cyrillus'),
  ('Du Pareil au Même'),
  ('Sergent Major'),
  ('Catimini'),
  ('IKKS'),
  ('Bonpoint'),
  ('Orchestra'),
  ('Gémo'),
  ('La Halle'),
  ('Tex'),
  ('In Extenso'),
  ('Intersport'),
  ('Go Sport'),
  ('C&A'),
  ('Lidl'),
  ('Aldi'),
  ('Ray-Ban'),
  ('Oakley'),
  ('Persol'),
  ('Vuarnet'),
  ('Police'),
  ('Carrera'),
  ('Prada Linea Rossa'),
  ('Swatch'),
  ('Casio'),
  ('Fossil'),
  ('Seiko'),
  ('Tissot'),
  ('Festina'),
  ('Lip'),
  ('Daniel Wellington'),
  ('Pandora'),
  ('Swarovski'),
  ('Eastpak'),
  ('Herschel'),
  ('Kipling'),
  ('Fjällräven'),
  ('JanSport'),
  ('Samsonite'),
  ('Delsey'),
  ('Le Tanneur'),
  ('Hermès'),
  ('Cartier'),
  ('Paris Saint-Germain'),
  ('Olympique de Marseille'),
  ('Olympique Lyonnais'),
  ('FC Nantes'),
  ('AS Saint-Étienne'),
  ('LOSC'),
  ('Real Madrid'),
  ('FC Barcelone'),
  ('Manchester United'),
  ('Manchester City'),
  ('Chelsea'),
  ('Liverpool'),
  ('Arsenal'),
  ('Juventus'),
  ('AC Milan'),
  ('Inter Milan'),
  ('Bayern Munich'),
  ('Borussia Dortmund'),
  ('FC Porto'),
  ('Benfica'),
  ('Équipe de France'),
  ('Team Vitality'),
  ('Karmine Corp'),
  ('Marvel'),
  ('DC Comics'),
  ('Disney'),
  ('Harry Potter'),
  ('Star Wars'),
  ('Pokémon'),
  ('Hellfest'),
  ('Apple'),
  ('Samsung'),
  ('Sony'),
  ('Nintendo'),
  ('Microsoft'),
  ('Xbox'),
  ('PlayStation'),
  ('Sega'),
  ('Huawei'),
  ('Xiaomi'),
  ('Google'),
  ('JBL'),
  ('Bose'),
  ('Beats'),
  ('Marshall'),
  ('Canon'),
  ('Nikon'),
  ('Pentax'),
  ('Olympus'),
  ('Fujifilm'),
  ('Panasonic'),
  ('Polaroid'),
  ('Kodak'),
  ('GoPro'),
  ('Lego'),
  ('Playmobil'),
  ('Mattel'),
  ('Hasbro'),
  ('Barbie'),
  ('Fisher-Price'),
  ('Vtech'),
  ('Asmodee'),
  ('Ikea'),
  ('Maisons du Monde'),
  ('Le Creuset'),
  ('Staub'),
  ('Tefal'),
  ('Moulinex'),
  ('Seb'),
  ('Arcopal'),
  ('Luminarc'),
  ('Pyrex'),
  ('Villeroy & Boch'),
  ('Banania'),
  ('Spidi'),
  ('Dainese'),
  ('Alpinestars'),
  ('Ixon'),
  ('Bering'),
  ('Furygan')
) AS m("nom")
WHERE NOT EXISTS (
  SELECT 1 FROM "marque" AS x WHERE x."utilisateur_id" = u."id" AND lower(x."nom") = lower(m."nom")
);
